version: '3.6'

services:
  mysql-local:
    container_name: mysql-local
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
      - TZ=Asia/Seoul
    command: [ "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci", "--max_connections=200", "--max_allowed_packet=100MB" ]
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
  redis-local:
    container_name: redis-local
    image: redis:6.0.6
    ports:
      - "6379:6379"