websocket.datasource.cluster:
  jdbc-url:
  driver-class-name: org.mariadb.jdbc.Driver
  username:
  password:
  maximum-pool-size:
  pool-name: websocket-datasource
  auto-commit: false
  data-source-properties:
    connectTimeout: 10000
    socketTimeout: 30000
    enableClusterAwareFailover: true

---
spring.config.activate.on-profile: local

websocket.datasource.cluster:
  jdbc-url: jdbc:mariadb:aurora://localhost:3306/chat?rewriteBatchedStatements=true
  username: test
  password: test
  maximum-pool-size: 5

---
spring.config.activate.on-profile: dev

---
spring.config.activate.on-profile: beta

---
spring.config.activate.on-profile: prod
